services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki-service
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml
      - loki_data:/loki
    command: -config.file=/etc/loki/config.yml
    networks:
      - microservices-network
    restart: unless-stopped

volumes:
  loki_data:

networks:
  microservices-network:
    external: true